name: Scorecard analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: '22 17 * * 1' # https://crontab.guru/#22_17_*_*_1
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  issues: read
  pull-requests: read
  statuses: read
  # Needed for SARIF upload
  security-events: write

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif

      - uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
        with:
          sarif_file: results.sarif
